#!/usr/bin/with-contenv sh
set -e

ARIA2_DIR=${ARIA2_DIR:-"/usr/aria2/download"}

ARIA2_BT_MAX_PEERS=${ARIA2_BT_MAX_PEERS:-55}
ARIA2_BT_REQUEST_PEER_SPEED_LIMIT=${ARIA2_BT_REQUEST_PEER_SPEED_LIMIT:-5M}

ARIA2_MAX_OVERALL_UPLOAD_LIMIT=${ARIA2_MAX_OVERALL_UPLOAD_LIMIT:-5M}

ARIA2_BT_EXCLUDE_TRACKER==${ARIA2_BT_EXCLUDE_TRACKER:-*}

ARIA2_DHT_LISTEN_PORT=${ARIA2_DHT_LISTEN_PORT:-6881}
ARIA2_ENABLE_DHT=${ARIA2_ENABLE_DHT:-true}
ARIA2_ENABLE_PEER_EXCHANGE=${ARIA2_ENABLE_PEER_EXCHANGE:-true}
ARIA2_LISTEN_PORT=${ARIA2_LISTEN_PORT:-6881}

ARIA2_DISK_CACHE=${ARIA2_LISTEN_PORT:-0}
ARIA2_FILE_ALLOCATION=${ARIA2_FILE_ALLOCATION:-none}

ARIA2_BT_MIN_CRYPTO_LEVEL=${ARIA2_BT_MIN_CRYPTO_LEVEL:-arc4}
ARIA2_BT_REQUIRE_CRYPTO=${ARIA2_BT_REQUIRE_CRYPTO:-true}

ARIA2_BT_TRACKER_CONNECT_TIMEOUT=${ARIA2_BT_TRACKER_CONNECT_TIMEOUT:-10}
ARIA2_BT_TRACKER_INTERVAL=${ARIA2_BT_TRACKER_INTERVAL:-900}
ARIA2_BT_TRACKER_TIMEOUT=${ARIA2_BT_TRACKER_TIMEOUT:-10}

ARIA2_FOLLOW_TORRENT=${ARIA2_FOLLOW_TORRENT:-mem}

ARIA2_SEED_RATIO=${ARIA2_SEED_RATIO:-0}
ARIA2_SEED_TIME=${ARIA2_SEED_TIME:-0}

ARIA2_LOWEST_SPEED_LIMIT=${ARIA2_LOWEST_SPEED_LIMIT:-10}

ARIA2_MAX_CONCURRENT_DOWNLOADS=${ARIA2_MAX_CONCURRENT_DOWNLOADS:-10}
ARIA2_MAX_CONNECTION_PER_SERVER=${ARIA2_MAX_CONNECTION_PER_SERVER:-1}
ARIA2_MIN_SPLIT_SIZE=${ARIA2_MIN_SPLIT_SIZE:-5M}
ARIA2_SPLIT=${ARIA2_SPLIT:-10}

ARIA2_RPC=${ARIA2_RPC:-true}
ARIA2_RPC_PORT=${ARIA2_RPC_PORT:-6800}
ARIA2_RPC_LISTEN_ALL=${ARIA2_RPC_LISTEN_ALL:-true}
ARIA2_RPC_SECRET=${ARIA2_RPC_SECRET}



mkdir -p /etc/aria2

echo dir=$ARIA2_DIR >> /etc/aria2/aria2.conf

echo bt-max-peers=$ARIA2_BT_MAX_PEERS >> /etc/aria2/aria2.conf
echo bt-request-peer-speed-limit=$ARIA2_BT_REQUEST_PEER_SPEED_LIMIT >> /etc/aria2/aria2.conf

echo max-overall-upload-limit=$ARIA2_MAX_OVERALL_UPLOAD_LIMIT >> /etc/aria2/aria2.conf

echo dht-listen-port=$ARIA2_DHT_LISTEN_PORT >> /etc/aria2/aria2.conf
echo enable-dht=$ARIA2_ENABLE_DHT >> /etc/aria2/aria2.conf
echo enable-peer-exchange=$ARIA2_ENABLE_PEER_EXCHANGE >> /etc/aria2/aria2.conf
echo listen-port=$ARIA2_LISTEN_PORT >> /etc/aria2/aria2.conf

echo disk-cache=$ARIA2_DISK_CACHE >> /etc/aria2/aria2.conf
echo file-allocation=$ARIA2_FILE_ALLOCATION >> /etc/aria2/aria2.conf

echo bt-min-crypto-level=$ARIA2_BT_MIN_CRYPTO_LEVEL >> /etc/aria2/aria2.conf
echo bt-require-crypto=$ARIA2_BT_REQUIRE_CRYPTO >> /etc/aria2/aria2.conf

echo bt-tracker-connect-timeout=$ARIA2_BT_TRACKER_CONNECT_TIMEOUT >> /etc/aria2/aria2.conf
echo bt-tracker-interval=$ARIA2_BT_TRACKER_INTERVAL >> /etc/aria2/aria2.conf
echo bt-tracker-timeout=$ARIA2_BT_TRACKER_TIMEOUT >> /etc/aria2/aria2.conf

echo follow-torrent=$ARIA2_FOLLOW_TORRENT >> /etc/aria2/aria2.conf

echo seed-ratio=$ARIA2_SEED_RATIO >> /etc/aria2/aria2.conf
echo seed-time=$ARIA2_SEED_TIME >> /etc/aria2/aria2.conf

echo lowest-speed-limit=$ARIA2_LOWEST_SPEED_LIMIT >> /etc/aria2/aria2.conf

echo max-concurrent-downloads=$ARIA2_MAX_CONCURRENT_DOWNLOADS >> /etc/aria2/aria2.conf
echo max-connection-per-server=$ARIA2_MAX_CONNECTION_PER_SERVER >> /etc/aria2/aria2.conf
echo min-split-size=$ARIA2_MIN_SPLIT_SIZE >> /etc/aria2/aria2.conf
echo split=$ARIA2_SPLIT >> /etc/aria2/aria2.conf

echo enable-rpc=$ARIA2_RPC >> /etc/aria2/aria2.conf
echo rpc-listen-port=$ARIA2_RPC_PORT >> /etc/aria2/aria2.conf
echo rpc-listen-all=$ARIA2_RPC_LISTEN_ALL >> /etc/aria2/aria2.conf
echo rpc-secret=$ARIA2_RPC_SECRET >> /etc/aria2/aria2.conf

mkdir -p $ARIA2_DIR
